### ISSUE TITLE
Does not work with rich editors

### ISSUE THREAD

**Issue by yeputons** [heisencoder/keyfixer#5]
Hi there,

I'm using <a href="https://asana.com">Asana</a> in Firefox on Mac (latest version of FF - 39.0).
KeyFixer works amazingly with single line text fields and simple textareas on other websites, but it does not work with rich editor which Asana uses for project description and task comments. It just behave as if there was no plug-in presented - Home scrolls the area up and End scrolls the area down.

**Comment by tadgy** [comment]
I've not tried FF 39 on my Mac as yet, and i'm not familiar with Asana; but I suspect - with absolutely no evidence to back me up - that it is some sort of Javascript based editor that provides a 'pretty' interface to editing.

If that's the case, the Javascript itself will likely be handling the navigation keys based upon it's own idea of what is correct and in an effort to make your editing "easier".  Basically, it knows better and how dare you not use it how the authors intended! :)

KeyFixer will likely not be able to help with any sort of Javascript edit boxes or fields because they are doing 'magic' behind the scenes to make everything fluffy for you.  KeyFixer works on the default input types of forms by mapping the keys to specific functions - if those are over-ridden by Javascript editors, you are stuffed, sorry :)

But then, I could be completely and utterly wrong - i'm not a dev for the project, but I have delved into the workings in order to submit a couple of patches in the past.  Let's see what the dev has to say about it.... :)

**Comment by heisencoder** [comment]
Without looking closely at Asana, I would tend to agree with tadgy.  Asana likely intercepts keystrokes on its own.  I don't think keyfixer will be able to help in this case.  Sorry!

**Comment by yeputons** [comment]
@heisencoder Actually, the problem is wider - it does not work with big amount of rich editors, like <a href="http://www.tinymce.com/tryit/full.php">TinyMCE</a>, <a href="http://showcase.richfaces.org/richfaces/component-sample.jsf?demo=editor">rich:editor</a>, <a href="http://www.quackit.com/html/online-html-editor/">quackit</a>'s editor, pretty anything that I was able to find quick. Works with Google Docs, though (however, I think it's Google who fixes keys in the editor).
